services:
    type: web
    name: telegram-bot
    env: python
    runtime: python-3.11.6 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_app.py"
    autoDeploy: true
